/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export * from './lecture-photo';
export * from './lecture';
export * from './people-counting-message';
export * from './photo-people-counting';
