/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LectureCreateInput {
  data: {
    description?: string;
    name: string;
  };
}

export interface LectureOptions {
  fetchPeopleCountingPhotos?: boolean;
  fetchPhotos?: boolean;
}

export interface LectureSearchInput {
  options?: LectureOptions;
  searchBy?: {
    id?: string;
    name?: string;
  };
}

export interface LectureUpdateInput {
  data: {
    description?: string;
    name?: string;
  };
  searchBy: {
    id: string;
  };
}
