/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LecturePhotoCreateInput {
  data: {
    image: string;
    lectureId: string;
  };
}

export interface LecturePhotoDeleteInput {
  searchBy: {
    imageId: string;
    lectureId: string;
  };
}
