version: "3.1"

networks:
  main_network:
    name: main_network

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./container_files/env-vars/.rabbitmq.prod.env
    networks:
      - main_network

  people_counting_service:
    container_name: people_counting_service_container
    build:
      context: ./people-counting-service
    restart: "no"
    env_file:
      - ./people-counting-service/container_files/env-vars/.prod.env
    networks:
      - main_network
    command:
      - python
      - main.py
    depends_on:
      - rabbitmq
  
  lectures_service:
    container_name: lectures_service_container
    ports:
      - "8000:8000"
    build:
      context: ./lectures-service
    restart: "on-failure:5"
    env_file:
      - ./lectures-service/env-vars/.prod.env
    networks:
      - main_network
    command:
      - node
      - -r
      - ./scripts/prod-setup.js
      - dist/main/index.js
    depends_on:
      - rabbitmq
